### ISSUE TITLE
Return not a number (NaN) instead of throwing an exception

### ISSUE THREAD

**Issue by asednev** [dkackman/LinqStatistics#3]
Please consider returning NaN instead of throwing an exception for cases when reasonable value can't be computed like when calculating variance of fewer than 2 elements:

https://github.com/dkackman/LinqStatistics/blob/master/LinqStatistics/EnumerableStatsVariance.cs#L148

Functions that throw exception require more stringent input validation which may not always be desired.

**Comment by dkackman** [comment]
I tried to model the signatures and behavior off of the built in [Enumerable ](http://referencesource.microsoft.com/#System.Core/System/Linq/Enumerable.cs,b7b87afe6c3fc715)extension methods so that they would be familiar. 

Enumerable.Average for instance throws when there are less than 2 elements.

Let me think about what a parallel implementation might look like as I do want to retain that symmetry to the built in linq methods.

**Comment by asednev** [comment]
Although in the past Enumerable.Average might have thrown for sequences of less than 2 elements, in .NET Framework 4.5 it's no longer the case. That's why we may have different understanding of how LinqStatistics behaves.

`
var avg = new[] { 1 }.Average(); // 1
`

**Comment by dkackman** [comment]
Right you are. Even previous versions of Average behaves that way since the average of one number is that number. What I was thinking of was the average of a sequence with no elements. 

    public static float Average(this IEnumerable<float> source)
    {
        if (source == null) throw Error.ArgumentNull("source");
        double sum = 0;
        long count = 0;
        checked
        {
            foreach (float v in source)
            {
                sum += v;
                count++;
            }
        }
        if (count > 0) return (float)(sum / count);
        throw Error.NoElements();
    }

The places where I'm throwing I see as similar in that the result of the operation is divide by zero.

    public static double Variance(this IEnumerable<int> source)
    {
        if (source == null)
            throw new ArgumentNullException("source");

        int n = 0;
        double mean = 0;
        double M2 = 0;

        foreach (var x in source)
        {
            n++;
                
            double delta = (double)x - mean;
            mean += delta / n;
            M2 += delta * ((double)x - mean);
        }

        if (n < 2)
            throw new InvalidOperationException("Source must have at least 2 elements");

        return (double)(M2 / (n - 1));
    }

**Comment by dkackman** [comment]
Please check out this branch: https://github.com/dkackman/LinqStatistics/tree/NaN.

Currently has only an implementation of Variance with the behavior you describe. In order to maintain current behavior and disambiguate resolution of the extension method, it's named VarianceNaN (for lack of a something better). It is also, currently in the namespace LinqStatistics.NaN, though the additional namespace is not strictly necessary, though it would allow anyone who prefers the Exception based behavior to avoid the clutter of an alternate implementation.

Let me know what you think of that approach.

**Comment by asednev** [comment]
@dkackman I like what you did, thank you so much. Separate namespace is a great way to separate two behaviors. If you go with namespaces, you can drop "NaN" part from "VarianceNaN" since "Variance" would be unique within that namespace. It's a matter of taste though.

**Comment by dkackman** [comment]
Since not all of the methods in the LinqStatistics namespace will have this alternate behavior I think I'll leave the NaN decoration on both the namespace and method names. CountEach forinstance won't be in the NaN namespace so if you want the NaN behavior and some of the other methods you will need both. Without decorating the method names as well there will be ambiguity between the implementations of Variance as extension methods even though the declaring classes are distinct.

The following for instance will not compile.

    using System;
    using System.Collections.Generic;

    namespace ConsoleApplication3.NaN
    {
        static class Functions
        {
            public static double Variance(this IEnumerable<int> data)
            {
                return double.NaN;
            }
        }
    }
    namespace ConsoleApplication3
    {

        static class Functions
        {
            public static double Variance(this IEnumerable<int> data)
            {
                throw new Exception();
            }
        }
    }

    namespace TheApp
    {
        using ConsoleApplication3;
        using ConsoleApplication3.NaN;
        class App
        {
            static void Main(string[] args)
            {
                var list = new List<int>();
                double v = list.Variance();
            }
        }
    }

**Comment by asednev** [comment]
You've got a point. I agree keeping NaN namespace makes sense in this case.

**Comment by dkackman** [comment]
Get the NaN branch and take a look. I think I got all those methods where it would make sense. Had to drop some integral value overloads. I've got to add some unit tests but I think this change set should cover it. https://github.com/dkackman/LinqStatistics/commit/186f570bcc3972e9ae576dcfd832d2196a945a51

**Comment by asednev** [comment]
I really like what you did. Only one place worth revisiting is covariance. There is validation for empty sequence which will prevent NaN from returning. I noticed that in many other functions you return NaN instead of throwing which is pretty awesome.

https://github.com/dkackman/LinqStatistics/blob/NaN/LinqStatistics/NaN/EnumerableStatsCovariance.cs#L44-L48

**Comment by asednev** [comment]
Btw, you were super helpful with this change. I will contribute some tests for NaN.

**Comment by asednev** [comment]
Do you see value in tests like these? https://github.com/asednev/LinqStatistics/tree/NaN/LinqStatisticsTests/NaN

**Comment by dkackman** [comment]
Definitely. Since we are forking the implementations it would also be good that have test that assert that methods like variance and vairancenan return the same result for valid input. This will ensure that the implementations domnt diverge.


So all tests are welcome. I'm out away from home until next week but will look at the covariance method and any pull requests you might have then.


Sent from Outlook Mobile






On Mon, Apr 18, 2016 at 10:59 PM -0700, "Alexey Sednev" <notifications@github.com> wrote:












Do you see value in tests like these? https://github.com/asednev/LinqStatistics/tree/NaN/LinqStatisticsTests/NaN

**Comment by dkackman** [comment]
I've fixed the covariance nan implementation. I'm going to merge this branch back into master if there is nothing else you notice amiss.

**Comment by dkackman** [comment]
Hey,

I've got it all merged to master. Please give it a test and give me a pull request with any unit tests you've got.

Thanks,
Don

**Comment by dkackman** [comment]
Implemented in release 2.1.0 https://github.com/dkackman/LinqStatistics/releases/tag/v2.1.0
